---
name: bluefin-zenbook
description: Custom Bluefin image for ASUS ZenBook UX393EA

base-image: ghcr.io/ublue-os/bluefin
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: bling
    install:
      - dconf-update-service

  - type: dnf
    repos:
      copr:
        - atim/starship
        - lukenukem/asus-linux
      files:
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
        - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
      nonfree: rpmfusion
    install:
      skip-unavailable: true
      allow-erasing: true
      packages:
        - atuin
        - bat
        - byobu
        - fd-find
        - ripgrep
        - tealdeer
        - ugrep
        - zoxide
        - starship
        - asusctl
        - thermald
        - intel-media-driver
        - libva-utils
        - tuned-ppd
        - powertop
        - intel-gpu-tools
        - cloudflare-warp
        - mullvad-vpn
        - virt-manager
        - podman-compose
        - cargo
    remove:
      packages:
        - firefox
        - firefox-langpacks 
        - power-profiles-daemon 

  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        install: 
          - org.mozilla.firefox
          - org.gnome.Loupe
          - net.mullvad.MullvadBrowser
      - notify: true
        scope: system
        repo:
          url: https://raw.githubusercontent.com/ShyVortex/helium-flatpak/refs/heads/main/helium.flatpakrepo
        include:
          - com.imputnet.Helium

  - type: systemd
    system:
      enabled:
        - asusd
        - thermald
        - tuned
      disabled:
        - mullvad-daemon.service
        - warp-svc.service

  - type: kargs
    kargs:
      - i915.force_probe=!9a49
      - xe.force_probe=9a49
      - i915.enable_psr=1
      - kernel.nmi_watchdog=0

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Alegreya
        - Cabin
        - Inter
        - Lato
        - Montserrat
        - Mulish
        - Open Sans
        - Roboto
        - Rubik

  - type: signing